const CACHE = 'atf-v62-runtime-1';
const SPRITE_MANIFEST = '/assets/openai/sprites/manifest.json';
const CORE = [
  '/', '/index.html', '/styles.css', '/styles-v50.css', '/sprite-gallery.css', '/hub-level.css', '/runtime-level.css', '/title-screen-v61.css', '/hub-stations-v61.css', '/catalog-v62.css', '/mission-insertion-v62.css',
  '/manifest.webmanifest', SPRITE_MANIFEST,
  '/docs/GAMEPLAY_PROMISE_AUDIT_V55.md', '/docs/V58_ROOM_COHERENCE_AUDIT.md',
  '/docs/VERSION_HISTORY_V59.md', '/docs/ART_PROVENANCE_V59.md',
  '/docs/references/V59_ASSET_COMPLETION_MATRIX.md',
  '/docs/VERSION_HISTORY_V60.md', '/docs/V60_LEVEL_DESIGN_AUDIT.md',
  '/docs/references/V60_ASSET_COMPLETION_MATRIX.md',
  '/docs/VERSION_HISTORY_V61.md', '/docs/VERSION_HISTORY_V62.md', '/docs/V61_LEVEL_DESIGN_AUDIT.md', '/docs/ART_PROVENANCE_V61.md', '/docs/ART_PROVENANCE_V62.md',
  '/docs/V62_IMPLEMENTATION_AUDIT.md', '/docs/references/V62_PNG_ALPHA_AUDIT.md', '/docs/references/V62_PNG_ALPHA_AUDIT.json',
  '/docs/references/V61_ASSET_COMPLETION_MATRIX.md', '/docs/references/V61_EXCEL_CONTENT_GAP_AUDIT.md',
  '/src/app.js', '/src/title-screen-v61.js', '/src/content.js', '/src/content-core-v50.js', '/src/visuals.js', '/src/v50-visuals.js',
  '/src/excel-content-bridge-v61.js', '/src/catalog-runtime-v62.js', '/src/catalog-ui-v62.js', '/src/forge-save-v62.js',
  '/src/infestation-chain-v62.js', '/src/mission-insertion-v62.js', '/src/mission-insertion-ui-v62.js',
  '/src/npc-dialogue-v62.js', '/src/vent-network-v62.js', '/src/hub-v62-runtime.js',
  '/src/save.js', '/src/advanced-systems.js', '/src/advanced-systems-core.js', '/src/world-crisis.js',
  '/src/world-crisis-core.js', '/src/campaign-consequences.js', '/src/game-production-runtime.js', '/src/game-production-core.js',
  '/src/game-production-resume.js', '/src/game-production-base.js', '/src/game-final-runtime.js',
  '/src/game-complete.js', '/src/game-complete-core.js', '/src/game-runtime.js', '/src/game-v51-runtime.js',
  '/src/game-v52-runtime.js', '/src/game-v52-level-runtime.js', '/src/sprite-animation-runtime.js', '/src/enemy-visual-runtime-v53.js', '/src/mission-levels-v52.js',
  '/src/enemy-visual-overrides-v55.js', '/src/enemy-visual-overrides-v56.js', '/src/npc-mission-runtime-v55.js',
  '/src/vehicle-visual-runtime-v55.js', '/src/vehicle-visual-overrides-v56.js',
  '/src/vehicle-access-runtime-v59.js', '/src/vehicle-deployment-gates-v60.js',
  '/src/weapon-visual-runtime-v56.js', '/src/weapon-visual-runtime-v61.js', '/src/equipment-visual-runtime-v56.js',
  '/src/mission-interactive-art-v56.js', '/src/mission-door-art-v58.js', '/src/topology-coherence-v58.js',
  '/src/hub-art-runtime-v55.js', '/src/hub-art-runtime-v56.js', '/src/hub-art-runtime-v58.js',
  '/src/hub-v51-runtime.js', '/src/hub-v52-runtime.js', '/src/hub-game.js', '/src/hub-profiles-v53.js', '/src/editor.js', '/src/audio.js',
  '/assets/openai/ui/title/tantalus-frontier-title-background-v61.png',
  '/assets/openai/ui/dialogue/mara-vega-operations-v61.png',
  '/assets/openai/ui/dialogue/sanaa-doyle-armory-v61.png',
  '/assets/openai/ui/customization/echo9-customization-mannequin-v61.png',
  '/assets/openai/hub/props/operations-table-v61.png',
  '/assets/openai/hub/props/armory-counter-v61.png',
  '/assets/openai/hub/props/hangar-control-booth-v61.png',
  '/assets/openai/hub/vents/tantalus-duct-interior-v62.png',
  '/assets/openai/mission/insertion/tantalus-dropship-approach-v62.png',
  '/assets/openai/mission/insertion/tantalus-apc-approach-v62.png',
  '/assets/openai/mission/insertion/tantalus-foot-approach-v62.png',
  '/assets/openai/hub/props/bulkhead-door.png',
  '/assets/openai/hub/props/lift-door.png',
  '/assets/openai/hub/props/bridge-terminal.png',
  '/assets/openai/hub/props/cryopod.png',
  '/assets/openai/hub/props/bunk-module.png',
  '/assets/openai/hub/props/mess-table.png',
  '/assets/openai/hub/props/medical-bed.png',
  '/assets/openai/hub/props/lab-console.png',
  '/assets/openai/hub/props/quarantine-unit.png',
  '/assets/openai/hub/props/workbench.png',
  '/assets/openai/hub/props/vehicle-lift.png',
  '/assets/openai/hub/props/reactor-column.png',
  '/assets/openai/hub/props/life-support-scrubber.png',
  '/assets/openai/hub/props/sensor-console.png',
  '/assets/openai/sprites/normalized/player/echo9-marine-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/player/echo9-marine-combat-sheet.png',
  '/assets/openai/sprites/normalized/enemies/xenomorph-drone-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/enemies/xenomorph-drone-combat-sheet.png',
  '/assets/openai/sprites/normalized/enemies/xenomorph-warrior-combat-sheet.png',
  '/assets/openai/sprites/normalized/enemies/xenomorph-queen-combat-sheet.png',
  '/assets/openai/sprites/normalized/enemies/xenomorph-runner-action-sheet.png',
  '/assets/openai/sprites/normalized/enemies/ripper-queen-action-sheet.png',
  '/assets/openai/sprites/normalized/enemies/pathogen-mimic-action-sheet.png',
  '/assets/openai/sprites/normalized/enemies/pale-crucible-hunter-action-sheet.png',
  '/assets/openai/sprites/normalized/enemies/xenomorph-praetorian-action-sheet.png',
  '/assets/openai/sprites/normalized/enemies/xenomorph-spitter-action-sheet.png',
  '/assets/openai/sprites/normalized/enemies/ovomorph-cycle-sheet.png',
  '/assets/openai/sprites/normalized/enemies/chestburster-action-sheet.png',
  '/assets/openai/sprites/normalized/enemies/xenomorph-crusher-action-sheet.png',
  '/assets/openai/sprites/normalized/enemies/xenomorph-lurker-action-sheet.png',
  '/assets/openai/sprites/normalized/enemies/xenomorph-carrier-action-sheet.png',
  '/assets/openai/sprites/normalized/enemies/xenomorph-ravager-action-sheet.png',
  '/assets/openai/sprites/normalized/enemies/facehugger-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/enemies/neomorph-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/enemies/working-joe-combat-sheet.png',
  '/assets/openai/sprites/normalized/vehicles/m577-apc-action-sheet.png',
  '/assets/openai/sprites/normalized/vehicles/m577-command-apc-action-sheet.png',
  '/assets/openai/sprites/normalized/vehicles/m22a3-jackson-tank-action-sheet.png',
  '/assets/openai/sprites/normalized/vehicles/p-5000-powered-work-loader-action-sheet.png',
  '/assets/openai/sprites/normalized/vehicles/ud-4l-cheyenne-dropship-action-sheet.png',
  '/assets/openai/sprites/normalized/weapons/m41a-pulse-rifle-action-sheet.png',
  '/assets/openai/sprites/normalized/npcs/mara-vega-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/npcs/tamsin-velez-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/npcs/idris-kwan-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/npcs/noor-okafor-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/npcs/bishop-9-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/npcs/rook-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/npcs/sanaa-doyle-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/npcs/maksim-orlov-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/npcs/inez-harlow-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/npcs/david-8r-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/npcs/jun-park-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/npcs/asha-mbaye-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/npcs/pablo-reyes-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/npcs/echo-a-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/npcs/leila-s-rensen-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/npcs/cal-mercer-locomotion-sheet.png',
  '/assets/openai/sprites/normalized/npcs/mara-vega-mission-sheet.png',
  '/assets/openai/sprites/normalized/npcs/tamsin-velez-mission-sheet.png',
  '/assets/openai/sprites/normalized/npcs/idris-kwan-mission-sheet.png',
  '/assets/openai/sprites/normalized/npcs/noor-okafor-mission-sheet.png',
  '/assets/openai/sprites/normalized/npcs/bishop-9-mission-sheet.png',
  '/assets/openai/sprites/normalized/npcs/rook-mission-sheet.png',
  '/assets/openai/sprites/normalized/npcs/sanaa-doyle-mission-sheet.png',
  '/assets/openai/sprites/normalized/npcs/maksim-orlov-mission-sheet.png',
  '/assets/openai/metroidvania/tantalus-mission-far.png',
  '/assets/openai/metroidvania/tantalus-mission-mid.png',
  '/assets/openai/metroidvania/tantalus-mission-foreground.png',
  '/assets/openai/metroidvania/props/maintenance-pipe.png',
  '/assets/openai/metroidvania/props/ceiling-cables.png',
  '/assets/openai/metroidvania/props/foreground-pipes.png',
  '/assets/openai/metroidvania/props/floor-segment.png',
  '/assets/openai/metroidvania/props/short-ledge.png',
  '/assets/openai/metroidvania/props/breakable-panel.png',
  '/assets/openai/metroidvania/props/cargo-cover.png',
  '/assets/openai/metroidvania/props/supply-crates.png',
  '/assets/openai/metroidvania/props/warning-lamp.png',
  '/assets/openai/metroidvania/props/acid-floor-hazard.png',
  '/assets/openai/hub/layers/engineering-hangar-overhead.png',
  '/assets/openai/metroidvania/props/overhead-catwalk.png',
  '/assets/openai/metroidvania/props/drop-platform.png',
  '/assets/openai/metroidvania/props/wall-ladder.png',
  '/assets/openai/metroidvania/props/vent-entrance.png',
  '/assets/openai/hub/layers/engineering-hangar-foreground.png',
  '/assets/openai/metroidvania/props/electrical-arc-hazard.png',
  '/assets/openai/human-factions-animation-sheet.png',
  '/assets/openai/synthetic-android-animation-sheet.png',
  '/assets/openai/pathogen-fauna-animation-sheet.png',
  '/assets/openai/neuro-xeno-animation-sheet.png',
  '/assets/openai/combat-vfx-animation-sheet.png',
  '/assets/openai/metroidvania/colony-multiroute-far.png',
  '/assets/openai/metroidvania/colony-multiroute-mid.png',
  '/assets/openai/metroidvania/colony-multiroute-foreground.png',
  '/assets/openai/metroidvania/planet-exterior-far.png',
  '/assets/openai/metroidvania/planet-exterior-mid.png',
  '/assets/openai/metroidvania/planet-exterior-foreground.png',
  '/assets/openai/metroidvania/zones/planet-exterior/planet-approach-far.png',
  '/assets/openai/metroidvania/zones/planet-exterior/planet-approach-mid.png',
  '/assets/openai/metroidvania/zones/planet-exterior/planet-approach-foreground.png',
  '/assets/openai/metroidvania/zones/planet-exterior/planet-surface-far.png',
  '/assets/openai/metroidvania/zones/planet-exterior/planet-surface-mid.png',
  '/assets/openai/metroidvania/zones/planet-exterior/planet-surface-foreground.png',
  '/assets/openai/metroidvania/zones/planet-exterior/planet-ridge-far.png',
  '/assets/openai/metroidvania/zones/planet-exterior/planet-ridge-mid.png',
  '/assets/openai/metroidvania/zones/planet-exterior/planet-ridge-foreground.png',
  '/assets/openai/metroidvania/zones/planet-exterior/planet-caves-far.png',
  '/assets/openai/metroidvania/zones/planet-exterior/planet-caves-mid.png',
  '/assets/openai/metroidvania/zones/planet-exterior/planet-caves-foreground.png',
  '/assets/openai/metroidvania/zones/planet-exterior/planet-ruins-far.png',
  '/assets/openai/metroidvania/zones/planet-exterior/planet-ruins-mid.png',
  '/assets/openai/metroidvania/zones/planet-exterior/planet-ruins-foreground.png',
  '/assets/openai/metroidvania/zones/planet-exterior/planet-evac-far.png',
  '/assets/openai/metroidvania/zones/planet-exterior/planet-evac-mid.png',
  '/assets/openai/metroidvania/zones/planet-exterior/planet-evac-foreground.png',
  '/assets/openai/metroidvania/hazards/darkness-visibility-mask-cycle.png',
  '/assets/openai/metroidvania/hazards/fire-hazard-cycle.png',
  '/assets/openai/metroidvania/hazards/flood-ripple-splash-cycle.png',
  '/assets/openai/metroidvania/hazards/flood-waterline-tiles.png',
  '/assets/openai/metroidvania/hazards/radiation-exposure-cycle.png',
  '/assets/openai/metroidvania/hazards/steam-jet-cycle.png',
  '/assets/openai/metroidvania/hazards/vacuum-breach-airflow-cycle.png',
  '/assets/openai/metroidvania/hazards/vacuum-frost-debris-overlay.png',
  '/assets/openai/metroidvania/drops/ammo-drop-sheet.png',
  '/assets/openai/metroidvania/drops/armor-drop-sheet.png',
  '/assets/openai/metroidvania/drops/medkit-drop-sheet.png',
  '/assets/openai/metroidvania/drops/salvage-drop-sheet.png',
  '/assets/openai/metroidvania/drops/security-key-drop-sheet.png',
  '/assets/openai/metroidvania/terminals/colony-medical-archive-terminal-sheet.png',
  '/assets/openai/metroidvania/terminals/planet-field-archive-beacon-sheet.png',
  '/assets/openai/metroidvania/terminals/ship-command-archive-terminal-sheet.png',
  '/assets/openai/metroidvania/zones/ship-docking-far.png',
  '/assets/openai/metroidvania/zones/ship-docking-mid.png',
  '/assets/openai/metroidvania/zones/ship-docking-foreground.png',
  '/assets/openai/metroidvania/zones/ship-cargo-far.png',
  '/assets/openai/metroidvania/zones/ship-cargo-mid.png',
  '/assets/openai/metroidvania/zones/ship-cargo-foreground.png',
  '/assets/openai/metroidvania/zones/ship-engineering-far.png',
  '/assets/openai/metroidvania/zones/ship-engineering-mid.png',
  '/assets/openai/metroidvania/zones/ship-engineering-foreground.png',
  '/assets/openai/metroidvania/zones/ship-habitation-far.png',
  '/assets/openai/metroidvania/zones/ship-habitation-mid.png',
  '/assets/openai/metroidvania/zones/ship-habitation-foreground.png',
  '/assets/openai/metroidvania/zones/ship-command-far.png',
  '/assets/openai/metroidvania/zones/ship-command-mid.png',
  '/assets/openai/metroidvania/zones/ship-command-foreground.png',
  '/assets/openai/metroidvania/zones/ship-extraction-far.png',
  '/assets/openai/metroidvania/zones/ship-extraction-mid.png',
  '/assets/openai/metroidvania/zones/ship-extraction-foreground.png',
  '/assets/openai/hub/layers/command-bridge-overhead.png',
  '/assets/openai/hub/layers/command-bridge-foreground.png',
  '/assets/openai/hub/layers/command-briefing-overhead.png',
  '/assets/openai/hub/layers/command-briefing-foreground.png',
  '/assets/openai/hub/layers/command-cic-overhead.png',
  '/assets/openai/hub/layers/command-cic-foreground.png',
  '/assets/openai/hub/layers/command-cryo-overhead.png',
  '/assets/openai/hub/layers/command-cryo-foreground.png',
  '/assets/openai/hub/layers/habitat-quarters-overhead.png',
  '/assets/openai/hub/layers/habitat-quarters-foreground.png',
  '/assets/openai/hub/layers/habitat-mess-overhead.png',
  '/assets/openai/hub/layers/habitat-mess-foreground.png',
  '/assets/openai/hub/layers/habitat-medical-overhead.png',
  '/assets/openai/hub/layers/habitat-medical-foreground.png',
  '/assets/openai/hub/layers/habitat-lab-overhead.png',
  '/assets/openai/hub/layers/habitat-lab-foreground.png',
  '/assets/openai/hub/layers/industrial-quarantine-overhead.png',
  '/assets/openai/hub/layers/industrial-quarantine-foreground.png',
  '/assets/openai/hub/layers/industrial-armory-overhead.png',
  '/assets/openai/hub/layers/industrial-armory-foreground.png',
  '/assets/openai/hub/layers/industrial-workshop-overhead.png',
  '/assets/openai/hub/layers/industrial-workshop-foreground.png',
  '/assets/openai/hub/layers/industrial-vehicle-bay-overhead.png',
  '/assets/openai/hub/layers/industrial-vehicle-bay-foreground.png',
  '/assets/openai/hub/layers/engineering-reactor-overhead.png',
  '/assets/openai/hub/layers/engineering-reactor-foreground.png',
  '/assets/openai/hub/layers/engineering-life-support-overhead.png',
  '/assets/openai/hub/layers/engineering-life-support-foreground.png',
  '/assets/openai/hub/layers/engineering-sensors-overhead.png',
  '/assets/openai/hub/layers/engineering-sensors-foreground.png',
  '/assets/openai/metroidvania/props/mission-door-states-v58.png',
  '/assets/openai/metroidvania/zones/colony-multiroute/colony-approach-far.png',
  '/assets/openai/metroidvania/zones/colony-multiroute/colony-approach-mid.png',
  '/assets/openai/metroidvania/zones/colony-multiroute/colony-approach-foreground.png',
  '/assets/openai/metroidvania/zones/colony-multiroute/colony-habitat-far.png',
  '/assets/openai/metroidvania/zones/colony-multiroute/colony-habitat-mid.png',
  '/assets/openai/metroidvania/zones/colony-multiroute/colony-habitat-foreground.png',
  '/assets/openai/metroidvania/zones/colony-multiroute/colony-civic-far.png',
  '/assets/openai/metroidvania/zones/colony-multiroute/colony-civic-mid.png',
  '/assets/openai/metroidvania/zones/colony-multiroute/colony-civic-foreground.png',
  '/assets/openai/metroidvania/zones/colony-multiroute/colony-utility-far.png',
  '/assets/openai/metroidvania/zones/colony-multiroute/colony-utility-mid.png',
  '/assets/openai/metroidvania/zones/colony-multiroute/colony-utility-foreground.png',
  '/assets/openai/metroidvania/zones/colony-multiroute/colony-security-far.png',
  '/assets/openai/metroidvania/zones/colony-multiroute/colony-security-mid.png',
  '/assets/openai/metroidvania/zones/colony-multiroute/colony-security-foreground.png',
  '/assets/openai/metroidvania/zones/colony-multiroute/colony-landing-far.png',
  '/assets/openai/metroidvania/zones/colony-multiroute/colony-landing-mid.png',
  '/assets/openai/metroidvania/zones/colony-multiroute/colony-landing-foreground.png',
  '/assets/openai/hub/layers/command-bridge-far.png',
  '/assets/openai/hub/layers/command-bridge-mid.png',
  '/assets/openai/hub/layers/command-briefing-far.png',
  '/assets/openai/hub/layers/command-briefing-mid.png',
  '/assets/openai/hub/layers/command-cic-far.png',
  '/assets/openai/hub/layers/command-cic-mid.png',
  '/assets/openai/hub/layers/command-cryo-far.png',
  '/assets/openai/hub/layers/command-cryo-mid.png',
  '/assets/openai/hub/layers/habitat-quarters-far.png',
  '/assets/openai/hub/layers/habitat-quarters-mid.png',
  '/assets/openai/hub/layers/habitat-mess-far.png',
  '/assets/openai/hub/layers/habitat-mess-mid.png',
  '/assets/openai/hub/layers/habitat-medical-far.png',
  '/assets/openai/hub/layers/habitat-medical-mid.png',
  '/assets/openai/hub/layers/habitat-lab-far.png',
  '/assets/openai/hub/layers/habitat-lab-mid.png',
  '/assets/openai/hub/layers/industrial-quarantine-far.png',
  '/assets/openai/hub/layers/industrial-quarantine-mid.png',
  '/assets/openai/hub/layers/industrial-armory-far.png',
  '/assets/openai/hub/layers/industrial-armory-mid.png',
  '/assets/openai/hub/layers/industrial-workshop-far.png',
  '/assets/openai/hub/layers/industrial-workshop-mid.png',
  '/assets/openai/hub/layers/industrial-vehicle-bay-far.png',
  '/assets/openai/hub/layers/industrial-vehicle-bay-mid.png',
  '/assets/openai/hub/layers/engineering-hangar-far.png',
  '/assets/openai/hub/layers/engineering-hangar-mid.png',
  '/assets/openai/hub/layers/engineering-reactor-far.png',
  '/assets/openai/hub/layers/engineering-reactor-mid.png',
  '/assets/openai/hub/layers/engineering-life-support-far.png',
  '/assets/openai/hub/layers/engineering-life-support-mid.png',
  '/assets/openai/hub/layers/engineering-sensors-far.png',
  '/assets/openai/hub/layers/engineering-sensors-mid.png'
];

async function precacheV62() {
  const cache = await caches.open(CACHE);
  await cache.addAll(CORE);
  const response = await fetch(SPRITE_MANIFEST, { cache: 'no-store' });
  if (!response.ok) throw new Error(`Sprite manifest unavailable: ${response.status}`);
  const manifest = await response.json();
  const normalizedSprites = [...new Set((manifest.sheets || [])
    .map((sheet) => sheet.files?.normalized)
    .filter((path) => typeof path === 'string' && path.includes('/sprites/normalized/')))];
  await cache.addAll(normalizedSprites);
}

self.addEventListener('install', (event) => event.waitUntil(
  precacheV62().then(() => self.skipWaiting())
));

self.addEventListener('activate', (event) => event.waitUntil(
  caches.keys().then((keys) => Promise.all(keys.filter((key) => key !== CACHE).map((key) => caches.delete(key))))
    .then(() => self.clients.claim())
));

self.addEventListener('fetch', (event) => {
  if (event.request.method !== 'GET') return;
  event.respondWith(
    fetch(event.request).then((response) => {
      const clone = response.clone();
      caches.open(CACHE).then((cache) => cache.put(event.request, clone));
      return response;
    }).catch(() => caches.match(event.request).then((cached) => {
      if (cached) return cached;
      if (event.request.mode === 'navigate') return caches.match('/index.html');
      return Response.error();
    }))
  );
});
